<?php
    $_helper    = $this->helper('catalog/output');
    $_product   = $this->getProduct();

    $title      = array();
    $desc       = array();
    if ($_product->getShortDescription()) {
        $title[]    = $this->__('Quick Overview');
        $desc[]     = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
    }
    $block  = trim($this->getChildHtml('additional'));
    if ($block) {
        $title[]    = $this->__('Additional Information');
        $desc[]     = $block;
    }
    $block  = trim($this->getChildHtml('quickview_related'));
    if ($block) {
        $title[]    = $this->__('Related Products');
        $desc[]     = $block;
    }
    $block  = trim($this->getChildHtml('quickview_upsell'));
    if ($block) {
        $title[]    = $this->__('Upsell Products');
        $desc[]     = $block;
    }
    
    //$tabs = (int)Mage::getStoreConfig('quickview/settings/tabs', Mage::app()->getStore());
?>

<?php if ( $_product->getShortDescription() && count($title)==1 ): ?>
    <div class="short-description">
        <h2><?php echo $this->__('Quick Overview') ?></h2>
        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
    </div>
<?php else: ?>
    <div class="quickview_tabs_block">
        <ul class="tabs_title quickview_tabs">
            <?php foreach ($title AS $key => $value): ?>
                <li id="tabs_item<?php echo $key ?>" class="item active"><a href="javascript:;"><?php echo $value ?></a></li>
            <?php endforeach ?>
        </ul>
        <div class="tabs_content">
            <?php foreach ($desc AS $key => $value): ?>
                <div id="tabs_item<?php echo $key ?>_content"><?php echo $value ?></div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?> 

