<?php
$helper				= Mage::helper('lightboxes');
$rel				= $helper->getLightboxRel($helper->getConfig('lightbox_type'));
$class				= $helper->getLightboxRel($helper->getConfig('lightbox_type'));
if($helper->getConfig('lightbox_type') == 'fancybox'):
?>
<!-- FancyBox -->
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("a[rel=<?php echo $rel; ?>],a[rel=<?php echo $rel; ?>-main]").fancybox({
			<?php echo $helper->getFancyboxJsConfig(); ?>
		});

        jQuery("a[rel=<?php echo $rel; ?>-main].video").fancybox({
            <?php echo $helper->getFancyboxJsConfig(true); ?>
        });

        jQuery("a.video").click(function() {
            jQuery.fancybox({
                'padding'		: 0,
                'autoScale'		: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'title'			: this.title,
                'width'		: 680,
                'height'		: 495,
                'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type'			: 'swf',
                'swf'			: {
                    'wmode'		: 'transparent',
                    'allowfullscreen'	: 'true'
                }
            });

            return false;
        });

    });
</script>
<!-- //FancyBox -->
<?php
endif;
?>

<?php
    if($helper->getConfig('lightbox_type') == 'lightboxclone'):
?>
<!-- Lightbox Clone -->
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('a[rel=<?php echo $rel; ?>]').lightBox({
			<?php echo $helper->getLightboxcloneJsConfig(); ?>
		});

        jQuery("a.video").click(function() {
            jQuery.fancybox({
                'padding'		: 0,
                'autoScale'		: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'title'			: this.title,
                'width'		: 680,
                'height'		: 495,
                'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type'			: 'swf',
                'swf'			: {
                    'wmode'		: 'transparent',
                    'allowfullscreen'	: 'true'
                }
            });

            return false;
        });



    });
</script>
<!-- //Lightbox Clone -->
<?php
    endif;
?>

<?php
    if($helper->getConfig('lightbox_type') == 'pirobox'):
?>
<!-- Pirobox -->
<script type="text/javascript">
    jQuery(document).ready(function(){
       jQuery().piroBox({
			<?php echo $helper->getPiroboxJsConfig(); ?>
		});
        jQuery("a.video").click(function() {
            jQuery.fancybox({
                'padding'		: 0,
                'autoScale'		: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'title'			: this.title,
                'width'		: 680,
                'height'		: 495,
                'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type'			: 'swf',
                'swf'			: {
                    'wmode'		: 'transparent',
                    'allowfullscreen'	: 'true'
                }
            });

            return false;
        });

    });
</script>
<!-- //Pirobox -->
<?php
    endif;
?>
<?php
    if($helper->getConfig('lightbox_type') == 'piroboxextended'):
?>
<!-- PiroboxExtended -->
<script type="text/javascript">
    jQuery(document).ready(function(){
       jQuery().piroBox_ext({
			<?php echo $helper->getPiroboxExtendedJsConfig(); ?>
		});
        jQuery("a.video").click(function() {
            jQuery.fancybox({
                'padding'		: 0,
                'autoScale'		: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'title'			: this.title,
                'width'		: 680,
                'height'		: 495,
                'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type'			: 'swf',
                'swf'			: {
                    'wmode'		: 'transparent',
                    'allowfullscreen'	: 'true'
                }
            });

            return false;
        });
    });
</script>
<!-- //PiroboxExtended -->
<?php
    endif;
?>
<?php
    if($helper->getConfig('lightbox_type') == 'prettyphoto'):
?>
<!-- prettyPhoto -->
<script type="text/javascript">
    jQuery(document).ready(function(){
	   jQuery("a[rel^='prettyPhoto']").prettyPhoto({
		   <?php echo $helper->getPrettyphotoJsConfig(); ?>
	   });
        jQuery("a.video").click(function() {
            jQuery.fancybox({
                'padding'		: 0,
                'autoScale'		: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'title'			: this.title,
                'width'		: 680,
                'height'		: 495,
                'href'			: this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type'			: 'swf',
                'swf'			: {
                    'wmode'		: 'transparent',
                    'allowfullscreen'	: 'true'
                }
            });

            return false;
        });
    });
</script>
<!-- //prettyPhoto -->
<?php
    endif;
?>