<?php
    $_helper     = $this->helper('catalog/output');
    $_product    = $this->getProduct();
    $productId   = $_product->getId();
    $product_url = $this->getUrl('').$_product->getUrlPath();
?>
<div class="popup" id="popup<?php echo $productId?>" >
    <?php if ($this->_settings['navigation']): ?>
        <?php if ($this->_nextProductId): ?>
            <a class="next-product-view" href="javascript:;" onclick="quickview.slide(<?php echo $this->_nextProductId ?>)">next product</a>
        <?php endif ?>
        <?php if ($this->_previousProductId): ?>
            <a class="prev-product-view" href="javascript:;" onclick="quickview.slide(<?php echo $this->_previousProductId ?>)">prev product</a>
        <?php endif ?>
    <?php endif?>
    <div class="popup-header">
        <div class="product-name">
            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        </div>
        <a class="close-popup" onclick="quickview.close()" href="javascript:void(0);"></a>
    </div>
    <div class="main-popup">
        <script type="text/javascript">
            optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
        </script>
        <div class="product-view">
            <div class="product-essential">
                <?php $addtocart_url    = $this->getSubmitUrl($_product) ?>
                <form action="<?php echo $addtocart_url ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId() ?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> onsubmit="return false">

                    <div class="no-display">
                        <input type="hidden" name="product" id="popup_product_id" value="<?php echo $_product->getId() ?>" />
                        <input type="hidden" name="related_product" id="popup_related_products_field" value="" />
                        <input type="hidden" name="in_cart" id="product_in_cart" value="0" />
                    </div>
                    <div class="row-fluid">
                        <div class="product-img-box span6">
                            <?php echo $this->getChildHtml('media') ?>
                        </div>
    
                        <div class="product-shop span6">
                            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                            <?php echo $this->getChildHtml('alert_urls') ?>
                            <?php echo $this->getChildHtml('product_type_data') ?>
                            <?php echo $this->getTierPriceHtml() ?>
                            <?php echo $this->getChildHtml('extrahint') ?>
    
                            <?php if (!$this->hasOptions()):?>
                                <div class="add-to-box">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php if ( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                            <span class="or"><?php echo $this->__('OR') ?></span>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php echo $this->getChildHtml('addto') ?>
                                </div>
                                <?php echo $this->getChildHtml('extra_buttons') ?>
                            <?php elseif (!$_product->isSaleable()): ?>
                                <div class="add-to-box">
                                    <?php echo $this->getChildHtml('addto') ?>
                                </div>
                            <?php endif ?>
                            
                            <?php echo $this->getChildHtml('other') ?>
    
                            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                            <?php endif ?>
                            <?php echo $this->getChildHtml('quickview_tabs') ?>
                            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif ?>
                        </div>
                    </div>

                    <div class="clearer"></div>
                    
                </form>

            </div>
        </div>
        <div class="quickview_popup_alpha"></div>
    </div>
    <div class="popup-footer">
        <div class="goto-product-view">
            <a href="<?php echo $product_url?>">
                <?php echo $this->__('VIEW FULL PRODUCT DETAILS')?>
            </a>
        </div>
    </div>
    <?php if ($this->_settings['navigation']): ?>
        <div class="navigation_preview">
            <?php $products = $this->_productsPosition ?>
            <?php foreach($products AS $product): ?>

            <?php endforeach ?>
        </div>
    <?php endif ?>
</div>

